### PR TITLE
feat(general): change diff color encoding

### PR DESCRIPTION
**Pull request by akriese**
To red for deletion, yellow for pixel differences, green for insertion.

### CODE REVIEW

**Comment by akriese** [comment]
Tackles part of #269

**Review by a-miscellaneous — APPROVED** [review]
lgtm:
image

**Comment by akriese** [comment]
I've made the tooltip take either a string or a composable as input, which needed some refactoring. Now, we can display anything in the tooltip, one of which are colored circles for the legend.
Before:
Screenshot 2024-02-02 140155

After:
Screenshot 2024-02-02 141432

**Comment by zino212** [comment]
Very nice work with the refactoring for the tooltip. I struggled earlier with making it these flexible. :)

**Pull request merged**
