### PR TITLE
Fat/Uber Jar gradle task

### PR DESCRIPTION
**Pull request by fs3itz**

### CODE REVIEW

**Comment by akriese** [comment]
The commits are all duplicated here. Maybe squash them? If you need help, tell me :)

**Comment by akriese** [comment]
Set to draft until we solve the output path default problem

**Comment by akriese** [comment]
rebased onto main

**Comment by fs3itz** [comment]
rebased onto main

**Comment by akriese** [comment]
@fs3itz is the jar working for you?

**Review by akriese — APPROVED** [review]

**Pull request merged**
