### PR TITLE
feat(lib3): creating GUI for lib3

### LINKED ISSUE #49: Setup Library 3 (Research, design decisions) (Library 3)
## User story
1. As a user
2. 1I want to have a clear setup of the project
3. So that I can sucessfully work and extend the project. The subproject should be integrated and compatible to the other libraries. 

## Acceptance criteria
* Select the framework 
* UI: Electron application would be a possibility, or whatever seems to make sense, it just has to be a good graphic visualisation!
* Ensure that the functionality can come from Library 2 (e.g. data types etc.)
* Set up Library 3, such that it is compatible and in the same language like Library 2, because the data comes from Library 2. -> Consider the compatibility of data types 
* The GUI later should work stable and fast and it should run on ordinary Windows or Linux PCs, so that the work with the tool is effective and efficient.

### PR DESCRIPTION
**Pull request by AlperK61**
Closes #49

### CODE REVIEW

**Comment by a-miscellaneous** [comment]
next time create a branch instead of forking

**Comment by a-miscellaneous** [comment]
which issue does this close?

**Comment by a-miscellaneous** [comment]
if this is supposed to setup gui framework, then pretty sure this does not have to be a multiplatform project since we are going to create a webapp

**Comment by AlperK61** [comment]
setup for lib 3

**Comment by akriese** [comment]
You added some files into version control that shouldn't be:
- local.properties
- 2x Main.jar
- ktlint

You probably did that by running something like `git add -A`, which is not a good approach, as unwanted files may be added to git. Instead try adding only the files you want for a commit :)

**Comment by zino212** [comment]
Like Petro mentioned you apparently forked the repo and didn't clone it. If you want to I can help with setting up "properly" and we can create a new PR with only the wanted files like Anton said.
@AlperK61

**Pull request closed without merging**
