### PR TITLE
Extend CI pipeline

### LINKED ISSUE #146: Extend CI-Pipeline
## User story
1. As a user
2. I want to make sure that the code builds and passes all license checks
3. So that the software has high quality

## Acceptance criteria
* license check has been added to the CI-Pipeline
* build check (run on different os (linux, windows, mac)) has been added to the CI-Pipeline
* a merge request can be only merged, when the license check and the build check passed

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### PR DESCRIPTION
**Pull request by zino212**
Closes #146

Blocked by #164 

Needs to be rebased after merging license check, because the license checks otherwise fail

### CODE REVIEW

**Comment by a-miscellaneous** [comment]
#164 was merged, you can rebase

**Comment by zino212** [comment]
Sorry, should have squashed or something. Git confuses me every single time (:

**Comment by akriese** [comment]
We'll fix it tomorrow :)

**Review by a-miscellaneous — APPROVED** [review]
lgtm

**Pull request merged**
