### PR TITLE
created frame differentiator and saved it to file system

### LINKED ISSUE #7: Computation of the frame diff (Library 2)
## User story
1. As a software developer 
2. I am given two video files in a data type supported by Kotlin    
3. So that I can compute the difference between the two video files by e.g. computing the pixel-wise difference between each pixel in the two images. Then the output is the one video file containing the pixel-wise difference between both video files.

## Acceptance criteria
* The program should be stable and consider all the allowed input data types 
* The program has to be reliable, lossless and should not introduce any imprecision
* The program should work properly for video files that have a lossless compression 
* In case of an error, a helpful user information has to be provided
* For the final output, the the video file must be available/ accessible in the Kotlin program.

## Definition of done (DoD)
* All specifiec acceptance criterias are met 
* The feature branch is merged into the main branch and then closed
* The code is clearly documented 

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### LINKED ISSUE #8: Export of the diff video file (Library 2)
## User story
1. As a user 
2. I want / to receive the final video that contains the frame difference 
3. So that I can save the video on the file system   

## Acceptance criteria
* The input for this part is the video file accessible in the Kotlin program.

* The system must provide an graphical user interface or API for the user to select the path where the video should be stored on the file system.
* The user should be able to choose an output data type for the video file, but only lossless data types are allowed! 
* The video file should be exported from the program, in case of an error, a helpful error handling should be triggered
* An info message should be shown that states that the export was successful. 
* The program has to be reliable, lossless and should not introduce any imprecision

## Definition of done (DoD)
* All specifiec acceptance criterias are met 
* The feature branch is merged into the main branch and then closed
* The code is clearly documented 

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### PR DESCRIPTION
**Pull request by a-miscellaneous**
loop through given videos
create a difference frame
append dif frame to output video

closes #7 
closes #8

### CODE REVIEW

**Comment by simonsasse** [comment]
@a-miscellaneous I pushed some suggestions. The problem was that using one instance of `Java2DFrameConverter` for multiple frames did not work and returned the same frame over and over. Thus no differences could be found.
I also added some new sample videos that actually have a diff. There are still some weird artefacts on the generated diff video.. I hope they somehow come from my encoding software and are thus not bugs in the code. 
I suggest that you look at the changes I made and if you approve tell me, then I will approve and merge (You cannot review your own ticket)

**Comment by akriese** [comment]
I'm seeing this `Signed-off-by: a-miscellaneous <96189996+a-miscellaneous@users.noreply.github.com>` in your commit messages. Maybe you should set it so it shows your name and email? Like, the git config's `user.name` & `user.email`

**Comment by akriese** [comment]
> The problem was that using one instance of Java2DFrameConverter for multiple frames did not work and returned the same frame over and over.

The converter class seems to save the `bufferedImage` it creates in a protected variable, which is pretty much only used in the `getBufferedImage()` function in line 597. When calling `convert` again, it reuses that member instead of creating a new one, which is weird behaviour imo. (See lines 562, 603 ff in `Java2DFrameConverter.java`)

**Comment by a-miscellaneous** [comment]
> I'm seeing this `Signed-off-by: a-miscellaneous <96189996+a-miscellaneous@users.noreply.github.com>` in your commit messages. Maybe you should set it so it shows your name and email? Like, the git config's `user.name` & `user.email`

This is standard behaviour for some projects, gonna leave it out in future commits

**Comment by a-miscellaneous** [comment]
@simonsasse changes look good
merge at you your convenience

**Review by simonsasse — APPROVED** [review]

**Pull request merged**
