### PR TITLE
Apply Material Design 3

### LINKED ISSUE #194: Use Material 3 Theme for UI (Library 3)
## User story
1. As a user
2. I want the user interface to use the material 3 theme
3. So that its user friendly and has a nice look

## Acceptance criteria
* Material 3 Theme is added to the frontend (see https://developer.android.com/jetpack/compose/designsystems/material3)
* All components use the Material 3 design

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### PR DESCRIPTION
**Pull request by zino212**
Closes #194 

I changed most of the calls for androidx.compose.material to androidx.compose.material3 for an uniform ui.
The ui now looks really different.
I also changed the colors, so if a component uses a specified color, it now uses the specified color of the palette which can be set in DefaultTheme.kt

### CODE REVIEW

**Comment by AlperK61** [comment]
It looks really well.

but some small issues on the settings screen:

- the number of parameters is not fully visible
image

- the file path on upload mask button is not fully visible
 
image

**Comment by akriese** [comment]
@AlperK61 these issues existed before, at least on my side. It really depends on how scaled one uses the app. The texts will fully disappear if the window is sized down a lot. Not sure, if we can simply fix this in this PR

**Comment by zino212** [comment]
Do you think this PR can be merged then? @akriese 
I would rebase it then once all other GUI tickets are merged and also apply Material3 there for a fresh start in the next sprint.
I also spoke with the POs, the next sprint will have a ticket for finishing up on the UIs visual style so the style and colors are ready and uniform for the demo.

**Comment by AlperK61** [comment]
ok, I didn´t know that. I think that can be merged then

**Review by AlperK61 — APPROVED** [review]

**Pull request merged**
