### PR TITLE
feat(lib1): input

### LINKED ISSUE #3: Data Input API (Library 1)
## User story
1. As a User
2. I want import 1 to n images into the system
3. So that they can be further processed

## Acceptance criteria
* 1 to n images can be imported via a endpoint (clarify with technical team if rest endpoints are feasible)
* the question which data type we use for image import first is clarified and accordingly implemented (try png first)
* the images are held after import in a internal Kotlin data format, that represents images (Important: The image files is not saved on the file system!)
* the endpoint takes in addition to the images also a filename and hands it over to the image processing method together with the images
* the images and the filename should be handed over to the method that processes the images (see ticket #4 )

Hint: (resource) efficiency has to be considered, because it will run on head unit 

1 to n images; filename -> endpoint -> internal Kotlin data format, representing images; filename

### PR DESCRIPTION
**Pull request by akriese**
Closes #3

### CODE REVIEW

**Comment by akriese** [comment]
Note, that there is not much implemented yet, as the requirement switched (#25) to a Kotlin library (away from a standalone program).

**Review by fs3itz — APPROVED** [review]

**Comment by a-miscellaneous** [comment]
`javax.imageio.ImageIO` is not part of the Android platform.

why is there an extra function to assign the output path? It should already be known on instance creation

**Comment by akriese** [comment]
> `javax.imageio.ImageIO` is not part of the Android platform.

You're right. I wasn't thinking of that at the time. Will look out for other options.

> why is there an extra function to assign the output path? It should already be known on instance creation

Somehow, I thought, that an instance might be repurposed to create another video. Hence the setter. Obviously, when the on instance is responsible for one video, we should go back to the class parameter.

**Comment by akriese** [comment]
Closes #26

**Comment by akriese** [comment]
Info: I chose ByteArray as input type as it is the Kotlin representation of a java byte[] according to the documentation

**Review by fs3itz — APPROVED** [review]

**Pull request merged**
