### PR TITLE
fix(lib1): make javacv work in Android project

### PR DESCRIPTION
**Pull request by akriese**

### CODE REVIEW

**Comment by akriese** [comment]
Currently, the tests in the library cant be executed, because only the android builds are loaded...

**Comment by akriese** [comment]
btw, no manual importing of jar files should be needed here. Simply sync gradle and execute the tests or build the example app

**Review by zino212 — APPROVED** [review]
I am quite unhappy that you did find the fix so fast.
I spend hours trying things that didn't work out and you basically just looked into it for like 20 minutes xD

**Comment by akriese** [comment]
> 20 minutes
Was a little more than that. Yesterday, also more than an hour :)

**Pull request merged**
