### PR TITLE
feat(gui): setup project structure

### PR DESCRIPTION
**Pull request by akriese**
NOTE: This PR is a replacement for #73 and #80, as both of those were from branches of a personal fork.

@AlperK61 set up the project structure for the gui and I cleaned up his commits a bit. 

Please check out the code and try if it works for you. I havent the time to so yet unfortunately...

### CODE REVIEW

**Comment by akriese** [comment]
Rebased onto current main

**Comment by akriese** [comment]
Some refactoring and formatting

**Comment by akriese** [comment]
To the reviewers: Please point questions regarding the project setup towards @AlperK61.

**Comment by akriese** [comment]
@AlperK61 So, as I currently see it, you set this up for Android. How would be build a desktop version for e.g. Windows here?

**Comment by a-miscellaneous** [comment]
more details in the readme please

**Pull request closed without merging**
