### PR TITLE
feat(gui): time line with thumbnail preview and scrollbar

### LINKED ISSUE #122: Add a screen preview (Library 3)
## User story
1. As a user
2. I want to have a preview of the difference video in the timeline 
3. So that I can effectively and efficiently analyze the differences and jump to the differences. 

## Acceptance criteria
* Added or deleted frames should be clearly visible in the preview/ timeline, e.g. green: Video 1 has missing images; blue: Video 2 has missing images and a red frame means that there exists a pixel difference. 
* the video should be shown in the timeline as illustrated in the timeline below
* Below the preview, there has to be a scroll bar, so that the user can possibly scroll through the entire video! 
* All functionality form the timeline (see ticket #110) should still work
* Simplification: All the preview images should have the same size 
* Simplification: All images should be shown 
* As long as we are in the current focused timeline the frame indicator jumps to the position
* If the we jump to a frame that is outside the current timeline the frame indicator should be focused in the middle
* The frame indicator should be in the middle of the current frame preview
* the whole frame should be shown as a thumbnail
* ask PO if something is unclear
* Example how the preview might look like: 

image

Image
* E.g. it could like that: 

Image

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### PR DESCRIPTION
**Pull request by akriese**
Closes #122.

- [x] Implement general layout
- [x] Load correct thumbnails
- [x] Show section depending on scrollstate
- [x] Adapt onClick of timeline
- [x] Adapt navigation behaviour of the timeline when pressing buttons
- [x] Dynamically choose number of frames to show at the same time
- [x] Fix scrollbar overscroll bug
- [x] Place time line indicator on center of thumbnails
- [x] Spread frames over timeline evenly with short (<10 frames) videos 
- [x] Simple thumbnail cache
- [x] Show diff indices above timeline
- [x] Refactor insertion/deletion bitmap creation to lib2
- [x] Mouse wheel scroll on timeline (works with Shift+Scroll Up/down)
- [ ] Update user documentation

### CODE REVIEW

**Comment by akriese** [comment]
Rebased onto current main

**Comment by simonsasse** [comment]
I miss the percentage above the cursor.
Also the frame indices are scrolling relatively faster and further than the frames. I think they should be fixed to their frames.
The area in which the numbers live is broader than the timeline itself, that seems wrong.

https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/59832939/fa93065d-ee08-4b75-b301-eaefe35e4a0e

Also if there is an insertion or deletion, two frames are showing the fully green/blue screen. Any idea why?

Screenshot 2024-01-17 at 10 31 57

**Comment by AlperK61** [comment]
the reason why two frames are showing fully green/blue screen is because it is clearer at which point an insertion and at which point a deletion was made. it was agreed with the PO´s

**Comment by akriese** [comment]
Percentage indicator was taken out. We deemed it enough, as we also have the scroll bar for that now and an index for each frame.

The label bug is weird. Gonna look into that. Both boxes are the same width though. At least in theory.

Two frames being blue on an insertion/deletion is a thing that needs discussion indeed. The old display was simply wrong though, as the previous frame of the video with the missing frame was shown, which is not desirable

**Review by a-miscellaneous — APPROVED** [review]
LGTM

**Pull request merged**
